"""add escalation fields to tasks

Revision ID: 25390d11e854
Revises: d48480979137
Create Date: 2026-08-08 16:08:25.441695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25390d11e854'
down_revision: Union[str, Sequence[str], None] = 'd48480979137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_escalated', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('escalation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'escalation_reason')
    op.drop_column('tasks', 'is_escalated')
    # ### end Alembic commands ###
